### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MCF_HamsterKombat#17]
```
[MasterCryptoFarmBot] [00:08:35] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1541, microseconds=566199), 'exception': None, 'extra': {}, 'file': (name='Playground.py', path='C:\\Users\\FARM\\MasterCryptoFarmBot\\modules\\MCF_HamsterKombat\\utilities\\Playground.py'), 'function': 'http_request', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 354, 'message': '[Playground] 🟡  Unable to send request, retrying...', 'module': 'Playground', 'name': 'utilities.Playground', 'process': (id=1860, name='MainProcess'), 'thread': (id=2868, name='Thread-80 (handle_request)'), 'time': datetime(2024, 10, 8, 0, 8, 35, 492220, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'GMT Summer Time'))}
[MasterCryptoFarmBot] [00:08:35] [MCF_HamsterKombat] [ERROR] [Playground] 🔴 Error generating promo key: maximum recursion depth exceeded
```

**Comment by masterking32** [comment]
Do you have custom changes?

**Comment by tboy1337** [comment]
No I have none.

**Comment by masterking32** [comment]
We don't use Loguru Handler!

**Comment by tboy1337** [comment]
lol? idk what to say man I havnt made and changes to the code at all, I do have it installed via pip though.

**Comment by masterking32** [comment]
It’s not a high-priority issue, and overall, HamsterKombat is not my focus. If @Fy0urM wants to check it, that's fine. Otherwise, I don’t want to waste my time on this module

**Comment by Fy0urM** [comment]
If you can tell me how to get this error. I will try to investigate it. Without being able to replicate the problem, there is no way to investigate it.

**Comment by Fy0urM** [comment]
Considering that this is a single error and not a mass error, not having your system 1 in 1 I'm afraid it will not be possible to repeat this error.

**Comment by tboy1337** [comment]
Ive told you all I can really in the previous comments, I dont know what else I can tell you.

**Comment by Fy0urM** [comment]
All I can suggest is that you install a normal system, use a normal user with admin rights, install python normally and see if this error happens again, you can use a virtual machine so you don't damage yours or reinstall it.

**Comment by tboy1337** [comment]
This is a pretty normal setup, all I’m doing is using a non-admin windows account which is the recommended way, I don’t really want to go down the route of having a VM continually running.

**Comment by Fy0urM** [comment]
I repeat, the problem is personal. If I can't reproduce it, there's no way to research it. No one else has this problem but you.

**Comment by tboy1337** [comment]
one thing that I will note is that somehow the project does use `loguru` because I deleted all modules, confirmed they were all deleted and then ran `start_windows.cmd` and now somehow `loguru` is installed again.

**Comment by Fy0urM** [comment]
you can try using venv. create venv and run the bot in venv.

**Comment by tboy1337** [comment]
hang on loguru is in the requirements.txt lol

**Comment by Fy0urM** [comment]
of course, because loguru is used as a logger
