### ISSUE TITLE
Error claiming random Playground: 'keysPerDay'

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MCF_HamsterKombat#19]
Im seeing a lot of the following errors:

```
[MasterCryptoFarmBot] [14:17:16] [MCF_HamsterKombat] [ERROR] 🔴 Error claiming random Playground: 'keysPerDay'
```

 - OS: Windows 10 Pro x64
 - Browser: Firefox Default
 - Version: latest

**Comment by Fy0urM** [comment]
https://github.com/masterking32/MCF_HamsterKombat/commit/80fb939d6df065e2badb750db062720ce3e7957b
